config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :users
  
  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
    validates :title, presence: true
    validates :description, presence: true
    validates :end_date, presence: true
    
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
    has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username,:first_name, :last_name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :first_name, :last_name) }
        end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_filter :get_users
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order('end_date')
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :duration, :start_date, :end_date, :user_id, :check)
    end
    
    private
    def get_users
      @users = User.all.map {|user| [user.username, user.id]}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flass_class(type)
        case type
            when :success then "success"
            when :error then "warning"
            when :alert then "warning"
            when :notice then ""
            else  "info"
        end    
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Trello" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to 'Trello', root_path %>
          </h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
    
        <section class="top-bar-section">
        
        <!-- Right Nav Section -->
        <ul class="right">
          <li class"divider"></li>
          <% if user_signed_in? %>
              <li class="active">
                <%= link_to current_user.first_name + ' ' + current_user.last_name ,  edit_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
              </li>
          <% else %>
              <li class="active">
                <%= link_to 'Sign Up', new_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Sign In', new_user_session_path %>
              </li>
          <% end %>
        </ul>
      </section>
    </nav>
    
    <div class="row">
      <div class="columns large-12">
        <br>
        <% flash.each do |type, message| %>
        <div data-alert class="alert-box success radius <%= flass_class type %>">
          <%= message %>
          <a href="#" class="close">&times;</a>
        </div>
        <% end %>
        
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="row">
    <div class="columns large-4">
      <div class="field">
        <%= f.label :duration %><br>
        <%= f.time_select :duration %>
      </div>
    </div>
    <div class="columns large-4">
        <div class="field">
          <%= f.label :start_date %><br>
          <%= f.date_select :start_date %>
        </div>
      </div>
    <div class="columns large-4">
      <div class="field">
        <%= f.label :end_date %><br>
        <%= f.date_select :end_date %>
      </div>
    </div>
  </div>
  
  <div class="field">
    Finished Task
    <%= f.label :check %><br>
    <%= f.check_box :check %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: 'button' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task, class: 'button' %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="columns large-4 medium-6">
    <%= link_to 'New Task', new_task_path, class: 'button' %>
  </div>
  <div class="columns large-8 medium-6">
    <h1>Listing Tasks</h1>
  </div>
</div>

<div class="panel">
<h2 class="subheader">Unfinished Tasks</h2>
<div class="row">
  <div class="columns large-6 medium-6">
  <ul class="pricing-table">
    <h3 class="title">Expired Tasks</h3>
      <% @tasks.each do |task| %>
        <% 
        datenow = Time.now 
        %>
        <% if task.check == false && task.end_date < datenow %>
          <hr>
      <div class="row">
        <div class="columns large-7 medium-6">
        <blockquote>
          <%= task.title %>
          <cite><%= task.user.username %> - <%= time_ago_in_words(task.created_at) %> ago </cite>
          <ul class="no-bullet">
            <li>Termination date: <%= task.end_date %></li>
          </ul>
        </blockquote>
        </div>
        <div class="columns large-5 medium-6">
          <ul class="inline-list">
            <li class="button tiny secondary"><%= link_to 'Show', task %></li>
            <% if user_signed_in? %>
              <li class="button tiny secondary"><%= link_to 'Edit', edit_task_path(task) %></li>
              <li class="button tiny secondary"><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <% end %>
    <% end %>
    </ul>
    </div>
    
    <div class="columns large-6 medium-6">
    <ul class="pricing-table">
    <h3 class="title">Tasks Not Expired</h3>
    <% @tasks.each do |task| %>
      <% 
        datenow = Time.now 
      %>
        <% if task.check == false && task.end_date > datenow %>
        <hr>
        <div class="row">
          <div class="columns large-7 medium-6">
          <blockquote>
            <%= task.title %>
            <cite><%= task.user.username %> - <%= time_ago_in_words(task.created_at) %> ago </cite>
            <ul class="no-bullet">
              <li>Termination date: <%= task.end_date %></li>
            </ul>
          </blockquote>
          </div>
          <div class="columns large-5 medium-6">
            <ul class="inline-list">
              <li class="button tiny secondary"><%= link_to 'Show', task %></li>
              <% if user_signed_in? %>
                <li class="button tiny secondary"><%= link_to 'Edit', edit_task_path(task) %></li>
                <li class="button tiny secondary"><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <% end %>
      <% end %>
      </ul>
   </div>
   </div>
  </div>
  
  <div class="panel callout radius">
  <h2 class="subheader">Completed Tasks</h2>
    <% @tasks.each do |task| %>
      <% if task.check == true %>
      <hr>
      <div class="row">
        <div class="columns large-7 medium-6">
        <blockquote>
          <%= task.title %>
          <cite><%= task.user.username %> - <%= time_ago_in_words(task.created_at) %> ago </cite>
          <ul class="no-bullet">
            <li>Termination date: <%= task.end_date %></li>
          </ul>
        </blockquote>
        </div>
        <div class="columns large-5 medium-6">
          <ul class="inline-list">
            <li class="button small secondary"><%= link_to 'Show', task %></li>
            <% if user_signed_in? %>
              <li class="button small secondary"><%= link_to 'Edit', edit_task_path(task) %></li>
              <li class="button small secondary"><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<ul class="pricing-table">
        <li class="price">
          <strong>Title:</strong>
          <%= @task.title %>
        </li>
  <li class="description">
    <strong>Description:</strong>
    <%= @task.description %>
  </li>
  <li class="bullet-item">
    <strong>User:</strong>
    <%= @task.user.username %>
  </li>
  <li class="bullet-item">
    <strong>Start date:</strong>
    <%= @task.start_date %>
  </li>
  <li class="bullet-item">
    <strong>End date:</strong>
    <%= @task.end_date %>
  </li>
  <li class="bullet-item">
    <strong>Duration:</strong>
    <%= @task.duration %>
  </li>
  <li class="bullet-item">
    <strong>Finished:</strong>
    <%= @task.check %>
  </li>
</ul>

<%= link_to 'Edit', edit_task_path(@task), class: 'button' %>